[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "api"
  base = "frontend"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
